
services:
  api:
    build: ./product
    container_name: api
    ports:
      - "3000:3000"
    volumes:
      - ./product:/app  # Mapeia a pasta product para /app dentro do contêiner
      - /app/node_modules  # Evita conflito entre os módulos locais e os do container
    command: ["npm", "run", "dev"]
    environment:
      - NODE_ENV=development
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    container_name: app-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - app_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: app-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  app_pgdata:
