services:
  api:
    build: ./product
    container_name: api
    ports:
      - "3000:3000"
    volumes:
      - ./product:/app  
      - /app/node_modules 
    command: ["npm", "run", "dev"]
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  api-order:
    build: ./order
    container_name: api-order
    ports:
      - "3005:3005"
    volumes:
      - ./order:/app  
      - /app/node_modules 
    command: ["npm", "run", "dev"]
    environment:
      - NODE_ENV=development
   
  db:
    image: postgres:14
    container_name: app-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - app_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:management
    container_name: app-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"  
      - "15672:15672"  
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  app_pgdata:
  rabbitmq_data:
